baseURL: https://example.org/
languageCode: es-es 
title: Acme Corporation 
theme: basic


author: 
  facebook: "https://facebook.com/example" 
  twitter: "https://twitter.com/example" 
  email: "contact@example.org" 
  name: "Acme Corporation" 
  location: Zaragoza
  phone: (999) 999-9999 
  hours: "**Lunes-Viernes** 9:00AM - 6:00PM" 


asa
menu:
  main: 
    - identifier: television
      name: Television
      url: /television/canales
      weight: 40 
    - identifier: blogs
      name: blogs
      url: /blogs
      weight: 40 
    - identifier: viajes
      name: viajessss
      url: /viajes
      weight: 40 
    - identifier: curriculum  
      name: CURRICULUM
      url: /curriculum 
      weight: 50 
    - identifier: about 
      name: Acerca de 
      url: /about 
      weight: 100 
    - identifier: contact
      name: Contacto 
      url: /contacto 
      weight: 200 



params: 
  colorPickerEnabled: true
  color: "#4f46e5"
  copyright: "Copyright &copy; 2022 Acme Corporation. Todos los derechos reservados."
 


  footer:
  - title: About
    content: >
      Acme Corporation is the world's leading
      manufacturer of digital shapes. From squares and
      circles to triangles and hexagons, we have it
      all. Browse through our collection of various
      forms with different thicknesses and line styles.
      We shape the world. You live in it.      


  - title: Publicaciones recientes
    recents: blog
    recentCount: 7

  - title: Contact Us
    contact: true